global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Web;
global using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.JSInterop;
global using SponsorCheck.Web;
global using SponsorCheck.Web.Components;
global using SponsorCheck.Web.Models;
global using SponsorCheck.Web.Services;
