<Project>
  <PropertyGroup>
    <_EOSS_ThePackageId>__EOSS_PACKAGE_ID_RAW__</_EOSS_ThePackageId>
    <_EOSS_TasksDir>$(MSBuildThisFileDirectory)..\tasks\</_EOSS_TasksDir>
    <_EOSS_TasksAssembly Condition="'$(MSBuildRuntimeType)' == 'Core'">$(_EOSS_TasksDir)netstandard2.0\EnforceOssSponsorship.Tasks.dll</_EOSS_TasksAssembly>
    <_EOSS_TasksAssembly Condition="'$(MSBuildRuntimeType)' != 'Core'">$(_EOSS_TasksDir)net472\EnforceOssSponsorship.Tasks.dll</_EOSS_TasksAssembly>
    <_EOSS_HashListPath>$(MSBuildThisFileDirectory)EnforceOssSponsorship.SponsorHashes.txt</_EOSS_HashListPath>
  </PropertyGroup>

  <UsingTask TaskName="EnforceOssSponsorship.Tasks.VerifySponsorshipTask"
             AssemblyFile="$(_EOSS_TasksAssembly)" />

  <Target Name="_EOSS_Verify___EOSS_PACKAGE_ID__"
          BeforeTargets="BeforeBuild"
          Condition="'$(Configuration)' == 'Release'">
    <ItemGroup>
      <_EOSS___EOSS_PACKAGE_ID___Ref Include="@(PackageReference)" Condition="'%(Identity)' == '$(_EOSS_ThePackageId)'" />
      <_EOSS___EOSS_PACKAGE_ID___Ver Include="@(PackageVersion)"   Condition="'%(Identity)' == '$(_EOSS_ThePackageId)'" />
    </ItemGroup>

    <VerifySponsorshipTask
        ThePackageId="$(_EOSS_ThePackageId)"
        SponsorHashListPath="$(_EOSS_HashListPath)"
        IgnoredFromRef="%(_EOSS___EOSS_PACKAGE_ID___Ref.SponsorshipIgnored)"
        IgnoredFromVer="%(_EOSS___EOSS_PACKAGE_ID___Ver.SponsorshipIgnored)"
        LicensedUntilFromRef="%(_EOSS___EOSS_PACKAGE_ID___Ref.SponsorshipLicensedUntil)"
        LicensedUntilFromVer="%(_EOSS___EOSS_PACKAGE_ID___Ver.SponsorshipLicensedUntil)"
        GitHubFromRef="%(_EOSS___EOSS_PACKAGE_ID___Ref.GitHubSponsorAccount)"
        GitHubFromVer="%(_EOSS___EOSS_PACKAGE_ID___Ver.GitHubSponsorAccount)"
        OpenCollectiveFromRef="%(_EOSS___EOSS_PACKAGE_ID___Ref.OpenCollectiveSponsorAccount)"
        OpenCollectiveFromVer="%(_EOSS___EOSS_PACKAGE_ID___Ver.OpenCollectiveSponsorAccount)"
        PolarFromRef="%(_EOSS___EOSS_PACKAGE_ID___Ref.PolarSponsorAccount)"
        PolarFromVer="%(_EOSS___EOSS_PACKAGE_ID___Ver.PolarSponsorAccount)" />
  </Target>
</Project>
