<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net472</TargetFrameworks>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <DevelopmentDependency>true</DevelopmentDependency>
    <NoPackageAnalysis>true</NoPackageAnalysis>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <PackageTags>sponsors;sponsorship;build;msbuild;github;opencollective;polar;opensource;maintenance;fee</PackageTags>
    <PackageReadmeFile>nuget-readme.md</PackageReadmeFile>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <NoWarn>$(NoWarn);NU5128;NU5100</NoWarn>
    <UserSecretsId>0b81e813-4e7d-40f9-810b-9bd2cddd69e4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Utilities.Core" PrivateAssets="all" ExcludeAssets="Runtime" />
    <PackageReference Include="Microsoft.Build.Framework"      PrivateAssets="all" ExcludeAssets="Runtime" />
    <PackageReference Include="ProjectDefaults" PrivateAssets="all" />
    <PackageReference Include="System.Text.Json" />
    <PackageReference Include="Polyfill" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
    <Reference Include="System.Net.Http" />
  </ItemGroup>

  <ItemGroup>
    <None Include="build\SponsorCheck.targets" Pack="true" PackagePath="build\SponsorCheck.targets;buildMultiTargeting\SponsorCheck.targets" />
    <None Include="EmbeddedTemplates\ConsumerVerifier.targets" Pack="true" PackagePath="build\ConsumerVerifier.targets;buildMultiTargeting\ConsumerVerifier.targets" Visible="false" />
    <None Include="nuget-readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <Target Name="_SponsorCheck_PackTaskDlls" BeforeTargets="_GetPackageFiles">
    <ItemGroup>
      <None Include="bin\$(Configuration)\netstandard2.0\*.dll" Pack="true" PackagePath="tasks\netstandard2.0\" Visible="false" />
      <None Include="bin\$(Configuration)\net472\*.dll" Pack="true" PackagePath="tasks\net472\" Visible="false" />
    </ItemGroup>
  </Target>
</Project>
