global using System;
global using System.Collections.Generic;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Net;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Threading.Tasks;
global using Microsoft.Build.Framework;
global using TUnit.Core;
global using static VerifyTUnit.Verifier;
